import { invariantFailed } from "../../utils/errors/throwErrors";
import { MessageHandler } from "../../utils/structures/messageHandler";
import { ProofGenerationContext } from "../proofGenerationContext";
import { ConfigurationError } from "../proofProviderErrors";
import { UserModelParams } from "../userModelParams";

import { GeneratedRawContentItem } from "./commonStructures/generatedRawContent";
import { ProofGenerationMetadataHolder } from "./commonStructures/proofGenerationMetadata";
import { ProofVersion } from "./commonStructures/proofVersion";
import { ModelParams } from "./modelParams";
import { ProofProvider } from "./proofProvider";
import { ProofProviderInternal } from "./proofProviderInternal";
import { buildProofFixChat } from "./utils/chatFactory";

/**
 * This class represents a proof generated by `ProofProvider`.
 * It stores all the meta information of its generation.
 *
 * Moreover, it might support multiround generation: fixing, shortening, etc.
 * For this, a new version of this proof could be generated via `ProofProviderInternal.generateFromChat`.
 *
 * Multiround-generation parameters are specified at `ModelParams.multiroundProfile`.
 *
 * Same to `ProofProvider`, multiround-generation methods perform errors handling and logging (in the same way).
 * Same to `ProofProvider`, these methods could be overriden to change the behaviour (of the multiround generation).
 *
 * Finally, `GeneratedProof` keeps the previous proof versions (but not the future ones).
 */
export abstract class GeneratedProof<
    ResolvedModelParams extends ModelParams = ModelParams,
    ProofProviderType extends ProofProvider<
        UserModelParams,
        ResolvedModelParams,
        ProofProviderType,
        GeneratedProofType,
        ProofProviderInternalType
    > = any,
    GeneratedProofType extends GeneratedProof<
        ResolvedModelParams,
        ProofProviderType,
        GeneratedProofType,
        ProofProviderInternalType
    > = any,
    ProofProviderInternalType extends ProofProviderInternal<
        ResolvedModelParams,
        ProofProviderType,
        GeneratedProofType,
        ProofProviderInternalType
    > = any,
> {
    /**
     * An accessor for `ModelParams.multiroundProfile.maxRoundsNumber`.
     */
    readonly maxRoundsNumber: number;

    /**
     * Previous proof versions of the current `GeneratedProof` (including the latest one).
     * Only the last one (i.e. the latest) is allowed to have an incomplete `ProofVersion`.
     *
     * When this `GeneratedProof` is generated in a new round (for example, `fixProof` is called),
     * the `proofVersions` won't track the results (newer proof versions).
     * Completely new `GeneratedProof` objects will be returned,
     * having longer `proofVersions` stored inside.
     */
    readonly proofVersions: ProofVersion[];

    /**
     * Creates an instance of `GeneratedProof`.
     * Should be called only by `ProofProvider`, `ProofProviderInternal` or `GeneratedProof` itself.
     *
     * This constructor is capable of extracting the actual proof (its block of code)
     * from the input `proof` in case it is contaminated with plain text or any other surrounding symbols.
     * Namely, it extracts the block between `Proof.` and `Qed.` if they are present;
     * otherwise, takes the whole `proof`.
     */
    constructor(
        rawProof: GeneratedRawContentItem,
        readonly proofGenerationContext: ProofGenerationContext,
        readonly modelParams: ResolvedModelParams,
        protected readonly proofProviderInternal: ProofProviderInternalType,
        previousProofVersions: ProofVersion[] = []
    ) {
        // Make a copy of the previous proof versions
        this.proofVersions = [...previousProofVersions];

        // Save newly generated `proof`
        this.proofVersions.push({
            proof: GeneratedProof.removeProofQedIfNeeded(rawProof.content),
            rawProof: rawProof,
            diagnostic: undefined,
        });

        this.maxRoundsNumber =
            this.modelParams.multiroundProfile.maxRoundsNumber;
        if (this.maxRoundsNumber < this.proofVersions.length) {
            invariantFailed(
                "`GeneratedProof`",
                "proof cannot be instantiated: max rounds number ",
                `(${this.maxRoundsNumber}) has been already reached`
            );
        }
    }

    /**
     * @returns a proof of the latest version for this `GeneratedProof`.
     */
    get proof(): string {
        return this.lastProofVersion.proof;
    }

    /**
     *
     * @returns a raw proof object as it was generated by the `ProofProvider`.
     */
    get rawProof(): GeneratedRawContentItem {
        return this.lastProofVersion.rawProof;
    }

    protected get lastProofVersion(): ProofVersion {
        return this.proofVersions[this.proofVersions.length - 1];
    }

    /**
     * Initially generated proofs have version number equal to 1.
     * Each generation round creates `GeneratedProofs` with version = `this.versionNumber() + 1`.
     *
     * @returns version number of this `GeneratedProof`.
     */
    get versionNumber(): number {
        return this.proofVersions.length;
    }

    /**
     * This method doesn't check `ModelParams.multiroundProfile.fixedProofChoices`,
     * because they can be overriden via the function's parameters at the call.
     *
     * @returns whether this `GeneratedProof` is allowed to be fixed at least once.
     */
    canBeFixed(): Boolean {
        return this.nextVersionCanBeGenerated();
    }

    /**
     * @returns whether `maxRoundsNumber` allows to generate a newer version of this proof.
     */
    protected nextVersionCanBeGenerated(): Boolean {
        return this.versionNumber < this.maxRoundsNumber;
    }

    /**
     * Generates new `GeneratedProof`-s as fixes for the latest version of the current one.
     * This method performs errors-handling and logging the same way as `ProofProvider`'s methods do.
     *
     * When this method is called, the `diagnostic` of the latest proof version
     * is overwritten with the `diagnostic` parameter of the call.
     *
     * The default implementation is based on the generation from chat, namely,
     * it calls `ProofProviderInternal.generateFromChatImpl`.
     * If it is not the desired way, `fixProof` should be overriden;
     * however, maintaining all errors-handling and logging invariants and, perfectly, models scheduling.
     * Consider `ProofProviderInternal.scheduleLoggedGenerationAndHandleErrors` for help.
     *
     * @param diagnostic the diagnostic received from the compiler.
     * @param choices specifies the number of choices for generation. If not provided, the `params.multiroundProfile.defaultProofFixChoices` value is used.
     * @param metadataHolder if provided, stores metadata about the proof generation process, which can be analyzed later.
     */
    async fixProof(
        diagnostic: string,
        choices: number = this.modelParams.multiroundProfile
            .defaultProofFixChoices,
        metadataHolder: ProofGenerationMetadataHolder | undefined = undefined,
        abortSignal?: AbortSignal,
        onSchedulerDebugLog: MessageHandler = this.proofProviderInternal
            .sendDebugEventOnSchedulerLog
    ): Promise<GeneratedProofType[]> {
        return this.proofProviderInternal.generateFromChatWrapped(
            this.modelParams,
            choices,
            metadataHolder,
            abortSignal,
            onSchedulerDebugLog,
            () => {
                if (!this.canBeFixed()) {
                    throw new ConfigurationError(
                        `this \`GeneratedProof\` could not be fixed: version ${this.versionNumber} >= max rounds number ${this.maxRoundsNumber}`
                    );
                }
                this.lastProofVersion.diagnostic = diagnostic;
                return buildProofFixChat(
                    this.proofGenerationContext,
                    this.proofVersions,
                    this.modelParams
                );
            },
            (rawProof) =>
                this.proofProviderInternal.constructGeneratedProof(
                    rawProof,
                    this.proofGenerationContext,
                    this.modelParams,
                    this.proofVersions
                )
        );
    }

    private static readonly coqProofBlockPattern =
        /(Proof(?:\s+using(?:\s+\w+)*)?)\.\s*(.*?)\s*(Qed|Defined|Admitted|Abort)\./s;
    private static readonly coqProofBlockStartPattern = [
        "Proof.",
        "Proof using.",
    ];
    private static readonly coqProofBlockEndPattern = [
        "Qed.",
        "Admitted.",
        "Defined.",
        "Abort.",
    ];

    // TODO: move to utils to improve testability
    static removeProofQedIfNeeded(message: string): string {
        const match = this.coqProofBlockPattern.exec(message);
        if (match) {
            return match[2];
        } else {
            if (
                this.coqProofBlockStartPattern.some((pattern) =>
                    message.includes(pattern)
                )
            ) {
                return message.split(this.coqProofBlockStartPattern[0])[1];
            } else if (
                this.coqProofBlockEndPattern.some((pattern) =>
                    message.includes(pattern)
                )
            ) {
                return message.split(this.coqProofBlockEndPattern[0])[0];
            }

            return message;
        }
    }
}
